name: import-gpg

on:
  push:
    branches: main

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      -
        name: List keys
        run: |
          gpg -K
          touch /tmp/gpg.txt
          #export GPG_TTY=`tty`
          gpg --batch -v --local-user F57FACF7D95135183C15AB6B409192A195AFD6C9 --output /tmp/gpg.encr --detach-sign /tmp/gpg.txt
